### ISSUE TITLE
Custom fields

### ISSUE THREAD

**Issue by mhipo1364** [puentesarrin/mongodb-log#5]
Hi

Thanks for creating this package, I have a question, How can I add some custom fields in logs?

**Comment by puentesarrin** [comment]
Hey Moe!

Standard Python logging module allows us to pass an `extra` dictionary argument on logging calls and the record will include the items of this dictionary. For instance, you can do something like this:

```
>>> log.debug('Some message', extra={'foo': 'bar'})
```

And the document saved in MongoDB will contain that field named `"foo"` with a value of `"bar"`. Does it work for you?

Hope it helps!

**Comment by mhipo1364** [comment]
Really thanks :+1:

**Comment by puentesarrin** [comment]
My pleasure.
