### ISSUE TITLE
NameError: name 'unicode' is not defined

### ISSUE THREAD

**Issue by anirudhagar13** [puentesarrin/mongodb-log#7]
'unicode' not defined in Python3. Instead str should be used to support Python3.

**Comment by banekillgrind** [comment]
So I had this issue pop up as well. Did you import classes instead of the whole library? I submitted a pull request earlier without really understanding the problem.

**Comment by banekillgrind** [comment]
#9 this is what I got

**Comment by puentesarrin** [comment]
Hey @anirudhagar13 and @banekillgrind,

Thanks for your report, I've just released a new version of this library that fixes the issue you pointed.

Thanks for your patience.
